name: deploy-container
on:
  push:
    branches:
      - master
    paths:  
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      metadata: write   # This is required for requesting the JWT
      contents: write 
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
     
      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify the appropriate region

      # Sync the build directory to S3
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container --delete